//! /proc Filesystem — Process & System Information
//!
//! Provides a virtual filesystem exposing kernel and process state
//! as readable files, inspired by Linux's procfs.
//!
//! Two independent interfaces are offered:
//!
//! 1. **Shell helper** — `read_procfs(path)` prints proc entries to the serial
//!    console. Used by the kernel debug shell. Unchanged from before.
//!
//! 2. **VFS-mounted filesystem** — `ProcFs` implements `FileSystemOps` and is
//!    mounted at `/proc` by `vfs::init()`.  Every `read()` call generates fresh
//!    content from live kernel state so userspace programs see up-to-date data.
//!
//! # Inode layout (ProcFs-internal; never exposed across a mount boundary)
//! ```
//! 2000  /proc (root dir)
//! 2001  cpuinfo
//! 2002  meminfo
//! 2003  uptime
//! 2004  version
//! 2005  mounts
//! 2006  cmdline  (kernel command line — NOT /proc/self/cmdline)
//! 2010  self/    (directory — resolved to caller's /proc/<pid>/ by VFS open)
//! 2011  self/maps
//! 2012  self/status
//! 2013  self/cmdline
//! 2014  self/stat
//! 2015  self/exe
//! 2016  self/comm
//! 2017  self/environ
//! 2020  self/fd/ (directory)
//! 2030  sys/     (directory)
//! 2031  sys/vm/  (directory)
//! 2032  sys/kernel/ (directory)
//! 2033  sys/kernel/random/ (directory)
//! 2040  sys/vm/overcommit_memory
//! 2041  sys/vm/max_map_count
//! 2042  sys/kernel/pid_max
//! 2043  sys/kernel/random/uuid
//! ```

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;

use super::{FileSystemOps, FileStat, FileType, VfsError, VfsResult};

// ── Inode constants ──────────────────────────────────────────────────────────

const INO_ROOT:              u64 = 2000;
const INO_CPUINFO:           u64 = 2001;
const INO_MEMINFO:           u64 = 2002;
const INO_UPTIME:            u64 = 2003;
const INO_VERSION:           u64 = 2004;
const INO_MOUNTS:            u64 = 2005;
const INO_CMDLINE:           u64 = 2006;
const INO_SELF_DIR:          u64 = 2010;
const INO_SELF_MAPS:         u64 = 2011;
const INO_SELF_STATUS:       u64 = 2012;
const INO_SELF_CMDLINE:      u64 = 2013;
const INO_SELF_STAT:         u64 = 2014;
const INO_SELF_EXE:          u64 = 2015;
const INO_SELF_COMM:         u64 = 2016;
const INO_SELF_ENVIRON:      u64 = 2017;
const INO_SELF_FD_DIR:       u64 = 2020;
const INO_SYS_DIR:           u64 = 2030;
const INO_SYS_VM_DIR:        u64 = 2031;
const INO_SYS_KERNEL_DIR:    u64 = 2032;
const INO_SYS_KERNEL_RAND:   u64 = 2033;
const INO_OVERCOMMIT:        u64 = 2040;
const INO_MAX_MAP_COUNT:     u64 = 2041;
const INO_PID_MAX:           u64 = 2042;
const INO_RAND_UUID:         u64 = 2043;

// ── ProcFs filesystem ────────────────────────────────────────────────────────

/// A read-only virtual filesystem mounted at `/proc`.
///
/// All inode numbers are fixed constants — there is no mutable state.
/// Content is generated fresh on every `read()` call.
pub struct ProcFs;

impl ProcFs {
    pub fn new() -> Self {
        ProcFs
    }

    /// Return the inode number used as the root of this mount.
    pub fn root_inode(&self) -> u64 {
        INO_ROOT
    }

    fn file_type_for(inode: u64) -> Option<FileType> {
        match inode {
            INO_ROOT
            | INO_SELF_DIR
            | INO_SELF_FD_DIR
            | INO_SYS_DIR
            | INO_SYS_VM_DIR
            | INO_SYS_KERNEL_DIR
            | INO_SYS_KERNEL_RAND => Some(FileType::Directory),

            INO_CPUINFO
            | INO_MEMINFO
            | INO_UPTIME
            | INO_VERSION
            | INO_MOUNTS
            | INO_CMDLINE
            | INO_SELF_MAPS
            | INO_SELF_STATUS
            | INO_SELF_CMDLINE
            | INO_SELF_STAT
            | INO_SELF_EXE
            | INO_SELF_COMM
            | INO_SELF_ENVIRON
            | INO_OVERCOMMIT
            | INO_MAX_MAP_COUNT
            | INO_PID_MAX
            | INO_RAND_UUID => Some(FileType::RegularFile),

            _ => None,
        }
    }

    /// Generate the content for inodes that don't require caller-PID context.
    /// Returns `None` for inodes whose content is generated by `vfs::fd_read()`
    /// special-case dispatch (maps, status, stat, cmdline — all need PID).
    fn generate_content(inode: u64) -> Option<Vec<u8>> {
        match inode {
            INO_CPUINFO => Some(generate_cpuinfo()),
            INO_MEMINFO => Some(generate_meminfo()),
            INO_UPTIME  => Some(generate_uptime()),
            INO_VERSION => Some(generate_version()),
            INO_MOUNTS  => Some(generate_mounts()),
            INO_CMDLINE => Some(b"astryx_kernel root=/dev/ramdisk0 console=fb0\n".to_vec()),
            // /proc/self/maps, /proc/self/status, /proc/self/stat, /proc/self/cmdline
            // are intercepted by fd_read() before fs.read() is called.
            // Return a non-empty stub so stat().size > 0 doesn't confuse callers.
            INO_SELF_MAPS     => Some(b"0000000000000000-0000000000001000 r--p 00000000 00:00 0 [vvar]\n".to_vec()),
            INO_SELF_STATUS   => Some(b"Name:\tastryx\nState:\tR (running)\nPid:\t1\nPPid:\t0\n".to_vec()),
            INO_SELF_CMDLINE  => Some(b"astryx\0".to_vec()),
            INO_SELF_STAT     => Some(b"1 (astryx) R 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 20 0 1 0 0 65536 0\n".to_vec()),
            INO_SELF_EXE      => Some(b"/disk/bin/init".to_vec()),
            INO_SELF_COMM     => Some(b"astryx\n".to_vec()),
            INO_SELF_ENVIRON  => Some(b"".to_vec()),
            INO_OVERCOMMIT    => Some(b"0\n".to_vec()),
            INO_MAX_MAP_COUNT => Some(b"65530\n".to_vec()),
            INO_PID_MAX       => Some(b"65536\n".to_vec()),
            INO_RAND_UUID     => Some(b"deadbeef-cafe-1234-5678-0a0b0c0d0e0f\n".to_vec()),
            _ => None,
        }
    }
}

impl FileSystemOps for ProcFs {
    fn name(&self) -> &str { "procfs" }

    fn lookup(&self, parent_inode: u64, name: &str) -> VfsResult<u64> {
        match (parent_inode, name) {
            (INO_ROOT, "cpuinfo")           => Ok(INO_CPUINFO),
            (INO_ROOT, "meminfo")           => Ok(INO_MEMINFO),
            (INO_ROOT, "uptime")            => Ok(INO_UPTIME),
            (INO_ROOT, "version")           => Ok(INO_VERSION),
            (INO_ROOT, "mounts")            => Ok(INO_MOUNTS),
            (INO_ROOT, "cmdline")           => Ok(INO_CMDLINE),
            (INO_ROOT, "self")              => Ok(INO_SELF_DIR),
            (INO_ROOT, "sys")               => Ok(INO_SYS_DIR),
            // /proc/<numeric-pid> — redirect to self (the VFS open() layer also
            // does this via redirect_proc_pid_path, but lookup may be called
            // directly without the redirect, e.g. from stat()).
            (INO_ROOT, name) if name.bytes().all(|b| b.is_ascii_digit()) && !name.is_empty() => {
                Ok(INO_SELF_DIR)
            }
            (INO_SELF_DIR, "maps")          => Ok(INO_SELF_MAPS),
            (INO_SELF_DIR, "status")        => Ok(INO_SELF_STATUS),
            (INO_SELF_DIR, "cmdline")       => Ok(INO_SELF_CMDLINE),
            (INO_SELF_DIR, "stat")          => Ok(INO_SELF_STAT),
            (INO_SELF_DIR, "exe")           => Ok(INO_SELF_EXE),
            (INO_SELF_DIR, "comm")          => Ok(INO_SELF_COMM),
            (INO_SELF_DIR, "environ")       => Ok(INO_SELF_ENVIRON),
            (INO_SELF_DIR, "fd")            => Ok(INO_SELF_FD_DIR),
            (INO_SYS_DIR,  "vm")            => Ok(INO_SYS_VM_DIR),
            (INO_SYS_DIR,  "kernel")        => Ok(INO_SYS_KERNEL_DIR),
            (INO_SYS_VM_DIR, "overcommit_memory") => Ok(INO_OVERCOMMIT),
            (INO_SYS_VM_DIR, "max_map_count")     => Ok(INO_MAX_MAP_COUNT),
            (INO_SYS_KERNEL_DIR, "pid_max")       => Ok(INO_PID_MAX),
            (INO_SYS_KERNEL_DIR, "random")        => Ok(INO_SYS_KERNEL_RAND),
            (INO_SYS_KERNEL_RAND, "uuid")         => Ok(INO_RAND_UUID),
            // /proc/self/fd/<N> — any numeric name is accepted (returns a stub inode)
            (INO_SELF_FD_DIR, _) if !name.is_empty() && name.bytes().all(|b| b.is_ascii_digit()) => {
                // Use the fd number as part of the inode.  The VFS readlink syscall
                // handles /proc/self/fd/<N> specially anyway.
                let n: u64 = name.parse().unwrap_or(0);
                Ok(3000 + n)
            }
            _ => Err(VfsError::NotFound),
        }
    }

    fn stat(&self, inode: u64) -> VfsResult<FileStat> {
        // Dynamic files report size 0 — callers must not rely on size for reads.
        // The VFS fd_read() path advances the offset through serve_dynamic_read()
        // which re-generates content on every read call.
        let file_type = Self::file_type_for(inode)
            .ok_or(VfsError::NotFound)?;
        let size = match file_type {
            FileType::RegularFile => {
                // Provide a non-zero size hint so callers that pre-allocate a
                // buffer based on stat().size get *something* reasonable.
                // Dynamic files may produce more or fewer bytes; callers must
                // handle short or extended reads.
                4096u64
            }
            FileType::Directory => 0,
            _ => 0,
        };
        Ok(FileStat {
            inode,
            file_type,
            size,
            permissions: match file_type {
                FileType::Directory   => 0o555,
                FileType::RegularFile => 0o444,
                _                     => 0o444,
            },
            created: 0,
            modified: 0,
            accessed: 0,
        })
    }

    fn read(&self, inode: u64, offset: u64, buf: &mut [u8]) -> VfsResult<usize> {
        // For inodes whose content is generated entirely here.
        let content = Self::generate_content(inode)
            .ok_or(VfsError::IsADirectory)?;
        let start = offset as usize;
        if start >= content.len() {
            return Ok(0);
        }
        let available = &content[start..];
        let n = available.len().min(buf.len());
        buf[..n].copy_from_slice(&available[..n]);
        Ok(n)
    }

    fn readdir(&self, inode: u64) -> VfsResult<Vec<(String, u64, FileType)>> {
        macro_rules! f { ($n:expr, $i:expr) => { (String::from($n), $i, FileType::RegularFile) }; }
        macro_rules! d { ($n:expr, $i:expr) => { (String::from($n), $i, FileType::Directory) }; }
        let entries: Vec<(String, u64, FileType)> = match inode {
            INO_ROOT => alloc::vec![
                f!("cpuinfo",  INO_CPUINFO),
                f!("meminfo",  INO_MEMINFO),
                f!("uptime",   INO_UPTIME),
                f!("version",  INO_VERSION),
                f!("mounts",   INO_MOUNTS),
                f!("cmdline",  INO_CMDLINE),
                d!("self",     INO_SELF_DIR),
                d!("sys",      INO_SYS_DIR),
            ],
            INO_SELF_DIR => alloc::vec![
                f!("maps",     INO_SELF_MAPS),
                f!("status",   INO_SELF_STATUS),
                f!("cmdline",  INO_SELF_CMDLINE),
                f!("stat",     INO_SELF_STAT),
                f!("exe",      INO_SELF_EXE),
                f!("comm",     INO_SELF_COMM),
                f!("environ",  INO_SELF_ENVIRON),
                d!("fd",       INO_SELF_FD_DIR),
            ],
            INO_SELF_FD_DIR => alloc::vec![],
            INO_SYS_DIR => alloc::vec![
                d!("vm",     INO_SYS_VM_DIR),
                d!("kernel", INO_SYS_KERNEL_DIR),
            ],
            INO_SYS_VM_DIR => alloc::vec![
                f!("overcommit_memory", INO_OVERCOMMIT),
                f!("max_map_count",     INO_MAX_MAP_COUNT),
            ],
            INO_SYS_KERNEL_DIR => alloc::vec![
                f!("pid_max", INO_PID_MAX),
                d!("random",  INO_SYS_KERNEL_RAND),
            ],
            INO_SYS_KERNEL_RAND => alloc::vec![
                f!("uuid", INO_RAND_UUID),
            ],
            _ => return Err(VfsError::NotADirectory),
        };
        Ok(entries)
    }

    // ── Unsupported write operations ─────────────────────────────────────────

    fn write(&self, _inode: u64, _offset: u64, _data: &[u8]) -> VfsResult<usize> {
        Err(VfsError::PermissionDenied)
    }

    fn create_file(&self, _parent: u64, _name: &str) -> VfsResult<u64> {
        Err(VfsError::PermissionDenied)
    }

    fn create_dir(&self, _parent: u64, _name: &str) -> VfsResult<u64> {
        Err(VfsError::PermissionDenied)
    }

    fn remove(&self, _parent: u64, _name: &str) -> VfsResult<()> {
        Err(VfsError::PermissionDenied)
    }

    fn truncate(&self, _inode: u64, _size: u64) -> VfsResult<()> {
        Err(VfsError::PermissionDenied)
    }
}

// ── Content generators ───────────────────────────────────────────────────────

/// Generate `/proc/cpuinfo` content using live CPUID data.
pub fn generate_cpuinfo() -> Vec<u8> {
    let mut out = Vec::new();

    // Query CPUID leaf 0 for vendor string.
    let (max_leaf, vendor) = {
        #[cfg(target_arch = "x86_64")]
        unsafe {
            let eax: u32;
            let ebx: u32;
            let ecx: u32;
            let edx: u32;
            core::arch::asm!(
                "push rbx",
                "cpuid",
                "mov {ebx_out:e}, ebx",
                "pop rbx",
                inout("eax") 0u32 => eax,
                ebx_out = out(reg) ebx,
                out("ecx") ecx,
                out("edx") edx,
            );
            let mut v = [0u8; 12];
            v[0..4].copy_from_slice(&ebx.to_le_bytes());
            v[4..8].copy_from_slice(&edx.to_le_bytes());
            v[8..12].copy_from_slice(&ecx.to_le_bytes());
            (eax, v)
        }
        #[cfg(not(target_arch = "x86_64"))]
        { (0u32, *b"Unknown     ") }
    };

    let vendor_str = core::str::from_utf8(&vendor).unwrap_or("Unknown");

    // Query CPUID leaf 1 for family/model/stepping + feature flags.
    let (family, model, stepping, features_edx, features_ecx) = if max_leaf >= 1 {
        #[cfg(target_arch = "x86_64")]
        unsafe {
            let eax: u32;
            let ecx: u32;
            let edx: u32;
            // rbx is reserved by LLVM — save/restore manually via push/pop.
            core::arch::asm!(
                "push rbx",
                "cpuid",
                "pop rbx",
                inout("eax") 1u32 => eax,
                out("ecx") ecx,
                out("edx") edx,
            );
            let stepping_id  = (eax >>  0) & 0xF;
            let model_id     = (eax >>  4) & 0xF;
            let family_id    = (eax >>  8) & 0xF;
            let ext_model    = (eax >> 16) & 0xF;
            let ext_family   = (eax >> 20) & 0xFF;
            let family = if family_id < 0xF {
                family_id
            } else {
                family_id + ext_family
            };
            let model = if family_id >= 6 {
                (ext_model << 4) | model_id
            } else {
                model_id
            };
            (family, model, stepping_id, edx, ecx)
        }
        #[cfg(not(target_arch = "x86_64"))]
        { (6u32, 0u32, 0u32, 0u32, 0u32) }
    } else {
        (6u32, 0u32, 0u32, 0u32, 0u32)
    };

    // Query CPUID leaf 0x80000002..0x80000004 for brand string.
    let brand = get_cpu_brand_string();

    // Build feature flag list from EDX leaf 1.
    let mut flags = alloc::vec::Vec::<&str>::new();
    if features_edx & (1 <<  0) != 0 { flags.push("fpu"); }
    if features_edx & (1 <<  4) != 0 { flags.push("tsc"); }
    if features_edx & (1 <<  5) != 0 { flags.push("msr"); }
    if features_edx & (1 <<  6) != 0 { flags.push("pae"); }
    if features_edx & (1 <<  9) != 0 { flags.push("apic"); }
    if features_edx & (1 << 15) != 0 { flags.push("cmov"); }
    if features_edx & (1 << 23) != 0 { flags.push("mmx"); }
    if features_edx & (1 << 24) != 0 { flags.push("fxsr"); }
    if features_edx & (1 << 25) != 0 { flags.push("sse"); }
    if features_edx & (1 << 26) != 0 { flags.push("sse2"); }
    if features_ecx & (1 <<  0) != 0 { flags.push("sse3"); }
    if features_ecx & (1 <<  1) != 0 { flags.push("pclmulqdq"); }
    if features_ecx & (1 <<  9) != 0 { flags.push("ssse3"); }
    if features_ecx & (1 << 19) != 0 { flags.push("sse4_1"); }
    if features_ecx & (1 << 20) != 0 { flags.push("sse4_2"); }
    if features_ecx & (1 << 23) != 0 { flags.push("popcnt"); }
    if features_ecx & (1 << 28) != 0 { flags.push("avx"); }
    if features_ecx & (1 << 30) != 0 { flags.push("rdrand"); }
    // Always include x86_64 baseline flags.
    flags.push("lm"); // long mode
    flags.push("nx"); // no-execute
    flags.push("syscall");

    let flags_str = flags.join(" ");
    let ticks = crate::arch::x86_64::irq::get_ticks();
    // Estimate MHz from ticks: we run at 100 Hz PIT, so each tick = 10ms.
    // This is a rough placeholder — real TSC calibration would be needed.
    let _ = ticks;

    let content = alloc::format!(
        "processor\t: 0\n\
         vendor_id\t: {vendor}\n\
         cpu family\t: {family}\n\
         model\t\t: {model}\n\
         model name\t: {brand}\n\
         stepping\t: {stepping}\n\
         cpu MHz\t\t: 2000.000\n\
         cache size\t: 4096 KB\n\
         flags\t\t: {flags}\n\
         bogomips\t: 4000.00\n\
         address sizes\t: 48 bits virtual, 39 bits physical\n\
         \n",
        vendor   = vendor_str,
        family   = family,
        model    = model,
        brand    = brand,
        stepping = stepping,
        flags    = flags_str,
    );
    out.extend_from_slice(content.as_bytes());
    out
}

/// Read the CPU brand string from CPUID leaves 0x80000002-0x80000004.
fn get_cpu_brand_string() -> String {
    #[cfg(target_arch = "x86_64")]
    {
        let max_ext = unsafe {
            let eax: u32;
            // rbx is reserved by LLVM — save/restore manually.
            core::arch::asm!(
                "push rbx",
                "cpuid",
                "pop rbx",
                inout("eax") 0x8000_0000u32 => eax,
                out("ecx") _,
                out("edx") _,
            );
            eax
        };
        if max_ext >= 0x8000_0004 {
            let mut brand = [0u8; 48];
            for i in 0u32..3 {
                let (a, b, c, d): (u32, u32, u32, u32) = unsafe {
                    let eax: u32; let ebx: u32; let ecx: u32; let edx: u32;
                    core::arch::asm!(
                        "push rbx",
                        "cpuid",
                        "mov {ebx_out:e}, ebx",
                        "pop rbx",
                        inout("eax") (0x8000_0002u32 + i) => eax,
                        ebx_out = out(reg) ebx,
                        out("ecx") ecx,
                        out("edx") edx,
                    );
                    (eax, ebx, ecx, edx)
                };
                let off = (i as usize) * 16;
                brand[off..off+4].copy_from_slice(&a.to_le_bytes());
                brand[off+4..off+8].copy_from_slice(&b.to_le_bytes());
                brand[off+8..off+12].copy_from_slice(&c.to_le_bytes());
                brand[off+12..off+16].copy_from_slice(&d.to_le_bytes());
            }
            // Trim leading spaces and trailing NULs.
            let trimmed = core::str::from_utf8(&brand)
                .unwrap_or("")
                .trim_matches('\0')
                .trim();
            if !trimmed.is_empty() {
                return String::from(trimmed);
            }
        }
    }
    String::from("QEMU Virtual CPU version 2.5+")
}

/// Generate `/proc/meminfo` content from live PMM stats.
pub fn generate_meminfo() -> Vec<u8> {
    let (total, used) = crate::mm::pmm::stats();
    let free = total.saturating_sub(used);
    let available = free;
    // Each PMM page = 4 KiB.
    let total_kb  = total    * 4;
    let free_kb   = free     * 4;
    let avail_kb  = available * 4;
    let content = alloc::format!(
        "MemTotal:       {total_kb:>8} kB\n\
         MemFree:        {free_kb:>8} kB\n\
         MemAvailable:   {avail_kb:>8} kB\n\
         Buffers:               0 kB\n\
         Cached:                0 kB\n\
         SwapCached:            0 kB\n\
         Active:                0 kB\n\
         Inactive:              0 kB\n\
         SwapTotal:             0 kB\n\
         SwapFree:              0 kB\n\
         Dirty:                 0 kB\n\
         Writeback:             0 kB\n\
         AnonPages:             0 kB\n\
         Mapped:                0 kB\n\
         Shmem:                 0 kB\n\
         PageSize:           4096 B\n",
        total_kb = total_kb,
        free_kb  = free_kb,
        avail_kb = avail_kb,
    );
    content.into_bytes()
}

/// Generate `/proc/uptime` content: `<seconds>.<hundredths> <idle_secs>.<hundredths>\n`.
pub fn generate_uptime() -> Vec<u8> {
    let ticks = crate::arch::x86_64::irq::get_ticks();
    let secs = ticks / 100;
    let frac = ticks % 100;
    alloc::format!("{secs}.{frac:02} {secs}.{frac:02}\n", secs = secs, frac = frac)
        .into_bytes()
}

/// Generate `/proc/version` content.
pub fn generate_version() -> Vec<u8> {
    b"Linux version 5.15.0-astryx (AstryxOS Aether 0.1 x86_64) #1 SMP AstryxOS\n".to_vec()
}

/// Generate `/proc/mounts` content from the live mount table.
fn generate_mounts() -> Vec<u8> {
    let mut out = alloc::vec::Vec::new();
    let mounts = crate::vfs::MOUNTS.lock();
    for m in mounts.iter() {
        let fstype = m.fs.name();
        let line = alloc::format!("{fstype} {path} {fstype} rw 0 0\n",
            fstype = fstype,
            path   = m.path);
        out.extend_from_slice(line.as_bytes());
    }
    out
}

// ── Legacy shell interface (unchanged) ──────────────────────────────────────

/// Read a /proc entry and display its contents to the serial console.
/// Used by the kernel debug shell — not involved in VFS file reads.
pub fn read_procfs(path: &str) {
    let clean = path.trim_start_matches('/');

    // Strip leading "proc/" if present
    let entry = if let Some(rest) = clean.strip_prefix("proc/") {
        rest
    } else if clean == "proc" || clean.is_empty() || clean == "/" {
        // List all entries
        crate::kprintln!("/proc:");
        crate::kprintln!("  cpuinfo");
        crate::kprintln!("  meminfo");
        crate::kprintln!("  uptime");
        crate::kprintln!("  version");
        crate::kprintln!("  net");
        crate::kprintln!("  mounts");
        crate::kprintln!("  cmdline");
        crate::kprintln!("  interrupts");
        crate::kprintln!("  processes");
        return;
    } else {
        clean
    };

    match entry {
        "cpuinfo"   => {
            let content = generate_cpuinfo();
            if let Ok(s) = core::str::from_utf8(&content) {
                crate::kprintln!("{}", s);
            }
        }
        "meminfo"   => {
            let content = generate_meminfo();
            if let Ok(s) = core::str::from_utf8(&content) {
                crate::kprintln!("{}", s);
            }
        }
        "uptime"    => {
            let content = generate_uptime();
            if let Ok(s) = core::str::from_utf8(&content) {
                crate::kprintln!("{}", s);
            }
        }
        "version"   => {
            let content = generate_version();
            if let Ok(s) = core::str::from_utf8(&content) {
                crate::kprintln!("{}", s);
            }
        }
        "net"       => show_net(),
        "mounts"    => {
            let content = generate_mounts();
            if let Ok(s) = core::str::from_utf8(&content) {
                crate::kprintln!("{}", s);
            }
        }
        "cmdline"   => crate::kprintln!("astryx_kernel root=/dev/ramdisk0 console=fb0"),
        "interrupts" => show_interrupts(),
        "processes" => show_processes(),
        _ => {
            if let Ok(_pid) = entry.parse::<u64>() {
                show_process_info(_pid);
            } else {
                crate::kprintln!("procfs: unknown entry '{}'", entry);
            }
        }
    }
}

fn show_net() {
    let mac = crate::net::our_mac();
    let ip = crate::net::our_ip();
    let gw = crate::net::gateway_ip();
    let mask = crate::net::subnet_mask();
    let (rx_p, tx_p, rx_b, tx_b) = crate::net::stats();
    let dns = crate::net::dns::get_nameserver();

    crate::kprintln!("Interface: eth0");
    crate::kprintln!("  HWaddr: {:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
        mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    crate::kprintln!("  IPv4:   {}.{}.{}.{}", ip[0], ip[1], ip[2], ip[3]);
    crate::kprintln!("  Mask:   {}.{}.{}.{}", mask[0], mask[1], mask[2], mask[3]);
    crate::kprintln!("  GW:     {}.{}.{}.{}", gw[0], gw[1], gw[2], gw[3]);
    crate::kprintln!("  DNS:    {}.{}.{}.{}", dns[0], dns[1], dns[2], dns[3]);
    crate::kprintln!("  RX:     {} packets, {} bytes", rx_p, rx_b);
    crate::kprintln!("  TX:     {} packets, {} bytes", tx_p, tx_b);
}

fn show_interrupts() {
    let ticks = crate::arch::x86_64::irq::get_ticks();
    crate::kprintln!("  IRQ  Count       Description");
    crate::kprintln!("  ---  ----------  -----------");
    crate::kprintln!("    0  {:>10}  PIT Timer (100 Hz)", ticks);
    crate::kprintln!("    1  {:>10}  PS/2 Keyboard", "N/A");
    crate::kprintln!("   11  {:>10}  e1000 NIC", "N/A");
}

fn show_processes() {
    crate::kprintln!("  PID  State       Name");
    crate::kprintln!("  ---  ----------  ----");
    let count = crate::proc::process_count();
    for pid in 0..count as u64 + 2 {
        if let Some(name) = crate::proc::process_name(pid) {
            crate::kprintln!("  {:>3}  Active      {}", pid, name);
        }
    }
}

fn show_process_info(pid: u64) {
    match crate::proc::process_name(pid) {
        Some(name) => {
            crate::kprintln!("PID:    {}", pid);
            crate::kprintln!("Name:   {}", name);
            crate::kprintln!("State:  Active");
            crate::kprintln!("TID:    {}", crate::proc::current_tid());
        }
        None => crate::kprintln!("Process {} not found", pid),
    }
}
