#!/usr/bin/env bash
#
# AstryxOS — Firefox Build Script (Phase 7)
#
# Cross-compiles Firefox ESR for AstryxOS using the dependency sysroot
# built by scripts/build-firefox-deps.sh.
#
# Target:     x86_64-linux-musl
# Firefox:    ESR 115 (latest long-term support release)
# Renderer:   Software/Cairo (no OpenGL/Wayland/X11)
# GUI:        AstryxOS native (custom integration layer)
#
# Prerequisites:
#   1. Run scripts/build-firefox-deps.sh first
#   2. sudo apt install rustup clang lld nasm python3-pip cbindgen
#      pip3 install --user mach
#
# Usage:
#   ./scripts/build-firefox.sh [--configure-only] [--skip-download]
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="${ROOT_DIR}/build"
SYSROOT="${BUILD_DIR}/sysroot"
SOURCES_DIR="${BUILD_DIR}/firefox-deps-src"
FF_DIR="${SOURCES_DIR}/firefox-esr"
FF_BUILD="${BUILD_DIR}/firefox-build"
FF_INSTALL="${BUILD_DIR}/firefox-install"
LOG_DIR="${BUILD_DIR}/firefox-deps-logs"
JOBS="$(nproc 2>/dev/null || echo 4)"
CONFIGURE_ONLY=false
SKIP_DOWNLOAD=false

FIREFOX_ESR_VER="115.15.0esr"
FIREFOX_URL="https://archive.mozilla.org/pub/firefox/releases/${FIREFOX_ESR_VER}/source/firefox-${FIREFOX_ESR_VER}.source.tar.xz"

for arg in "$@"; do
    case "$arg" in
        --configure-only) CONFIGURE_ONLY=true ;;
        --skip-download)  SKIP_DOWNLOAD=true  ;;
        --jobs) JOBS="$2"; shift ;;
    esac
done

mkdir -p "${SOURCES_DIR}" "${FF_BUILD}" "${LOG_DIR}"

# ── Verify sysroot exists ────────────────────────────────────────────────────

if [ ! -d "${SYSROOT}/lib" ]; then
    echo "ERROR: Sysroot not found at ${SYSROOT}"
    echo "Run: ./scripts/build-firefox-deps.sh"
    exit 1
fi

# ── Download Firefox ESR source ──────────────────────────────────────────────

if [ "${SKIP_DOWNLOAD}" = false ]; then
    ARCHIVE="${SOURCES_DIR}/firefox-${FIREFOX_ESR_VER}.source.tar.xz"
    if [ ! -f "${ARCHIVE}" ]; then
        echo "[DOWNLOAD] Fetching Firefox ESR ${FIREFOX_ESR_VER} source (~350 MB)..."
        wget -q --show-progress -O "${ARCHIVE}" "${FIREFOX_URL}"
    fi
    if [ ! -d "${FF_DIR}" ]; then
        echo "[EXTRACT] Extracting Firefox source..."
        mkdir -p "${FF_DIR}"
        tar -xf "${ARCHIVE}" -C "${FF_DIR}" --strip-components=1
    fi
fi

# ── Generate mach mozconfig ──────────────────────────────────────────────────

MOZCONFIG="${FF_BUILD}/mozconfig"
cat > "${MOZCONFIG}" <<EOF
# AstryxOS Firefox Build Configuration
# Generated by scripts/build-firefox.sh

# ── Target ─────────────────────────────────────────────────────────────────
ac_add_options --target=x86_64-linux-musl
ac_add_options --host=x86_64-linux-gnu

# ── Build type ─────────────────────────────────────────────────────────────
ac_add_options --enable-release
ac_add_options --enable-optimize="-O2"
ac_add_options --disable-debug
ac_add_options --disable-debug-symbols
ac_add_options --disable-tests

# ── Sysroot / toolchain ────────────────────────────────────────────────────
ac_add_options --with-sysroot=${SYSROOT}
ac_add_options --with-toolchain-prefix=x86_64-linux-musl-

# ── Renderer: software (no GL/Wayland/X11) ────────────────────────────────
ac_add_options --disable-webgl
ac_add_options --disable-webgl2
ac_add_options --disable-hardware-video-decoding
ac_add_options --disable-openh264
ac_add_options --disable-eme
ac_add_options --without-x
ac_add_options --without-wayland
ac_add_options --disable-dbus
ac_add_options --disable-cups

# ── GUI toolkit: headless (AstryxOS will provide its own window system) ──
ac_add_options --enable-application=browser
ac_add_options --with-gtk=none
ac_add_options --disable-glib
ac_add_options --disable-gio

# ── Dependency paths from sysroot ─────────────────────────────────────────
ac_add_options --with-system-zlib
ac_add_options --with-system-png
ac_add_options --with-system-libjpeg
ac_add_options --with-system-libvpx=no       # use bundled
ac_add_options --with-system-nspr=no         # use bundled
ac_add_options --with-system-nss=no          # use bundled
ac_add_options --with-system-icu=no          # use bundled
ac_add_options --with-system-sqlite=nspr    

# ── JavaScript engine ──────────────────────────────────────────────────────
ac_add_options --enable-jit                  # SpiderMonkey JIT (x86_64 = supported)
ac_add_options --disable-cranelift           # Wasm Cranelift (optional)
ac_add_options --disable-wasm-simd

# ── Compile options ────────────────────────────────────────────────────────
ac_add_options --disable-updater
ac_add_options --disable-crashreporter
ac_add_options --disable-maintenance-service
ac_add_options --disable-notifications
ac_add_options --disable-default-browser-agent
ac_add_options --disable-backgroundtasks

# ── Static linking ─────────────────────────────────────────────────────────
LDFLAGS="-L${SYSROOT}/lib -static-libstdc++ -static-libgcc"
CPPFLAGS="-I${SYSROOT}/include"
EOF

echo "[CONFIG] mozconfig written to ${MOZCONFIG}"
export MOZCONFIG

# ── Configure Firefox ────────────────────────────────────────────────────────

cat > "${FF_DIR}/.mozconfig" <<EOF
. "${MOZCONFIG}"
mk_add_options MOZ_OBJDIR=${FF_BUILD}
EOF

if [ "${CONFIGURE_ONLY}" = true ]; then
    echo "[CONFIG] Running ./mach configure only..."
    cd "${FF_DIR}" && ./mach configure 2>&1 | tee "${LOG_DIR}/firefox-configure.log"
    echo "[DONE] Configure complete. Build with: cd ${FF_DIR} && ./mach build"
    exit 0
fi

# ── Build Firefox ────────────────────────────────────────────────────────────

echo "[BUILD] Building Firefox ESR ${FIREFOX_ESR_VER}..."
echo "[BUILD] This will take 30-120 minutes depending on hardware."
echo "[BUILD] Logs: ${LOG_DIR}/firefox-build.log"

cd "${FF_DIR}"
./mach build -j"${JOBS}" 2>&1 | tee "${LOG_DIR}/firefox-build.log"

# ── Install into build/firefox-install/ ──────────────────────────────────────

mkdir -p "${FF_INSTALL}"
./mach install DESTDIR="${FF_INSTALL}" 2>&1 | tee "${LOG_DIR}/firefox-install.log"

# ── Package for AstryxOS data disk ──────────────────────────────────────────

echo "[PACKAGE] Copying Firefox binaries to data disk layout..."
mkdir -p "${BUILD_DIR}/disk/bin" "${BUILD_DIR}/disk/lib/firefox"

# Copy the main firefox binary
if [ -f "${FF_INSTALL}/usr/local/bin/firefox" ]; then
    cp "${FF_INSTALL}/usr/local/bin/firefox" "${BUILD_DIR}/disk/bin/firefox"
fi

# Copy the Firefox application files (XUL, resources, etc.)
if [ -d "${FF_INSTALL}/usr/local/lib/firefox" ]; then
    cp -r "${FF_INSTALL}/usr/local/lib/firefox/." "${BUILD_DIR}/disk/lib/firefox/"
fi

# ── Summary ──────────────────────────────────────────────────────────────────

echo
echo "╔══════════════════════════════════════════════════════╗"
echo "║   Firefox Build Complete                             ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║   Install:  ${FF_INSTALL}"
echo "║   Disk:     ${BUILD_DIR}/disk/"
echo "╠══════════════════════════════════════════════════════╣"
echo "║   Next: add disk/ to data.img via create-data-disk.sh║"
echo "╚══════════════════════════════════════════════════════╝"
