#!/usr/bin/env bash
# patch-gui-caches.sh — regenerate and/or inject the three GUI runtime cache
# files the windowed (--ff-gui) Firefox path needs into the staging tree and/or
# an existing ext2 data image, WITHOUT a full create-data-disk.sh rebuild.
#
# The three caches (all BINARY index files Alpine produces only as apk
# post-install trigger output, never as packaged files):
#
#   /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache   GdkPixbuf image loaders
#       — the kernel sets GDK_PIXBUF_MODULE_FILE to this absolute path
#         (kernel/src/gui/terminal.rs), so without it GDK icon decode degrades.
#   /usr/share/glib-2.0/schemas/gschemas.compiled  GSettings schema cache
#       — GtkSettings reads only the compiled cache; without it theme/icon-name
#         keys are unresolved and GTK warns "schema is not installed".
#   /usr/share/mime/mime.cache                     Shared-MIME database cache
#       — GIO content-type queries (g_content_type_guess) read it.
#
# These are generated by scripts/install-firefox-musl.sh (steps c1/c3) into
# build/disk/, and create-data-disk.sh then snaps build/disk into the ext2
# data.img with mke2fs -d.  A data image built BEFORE those steps existed
# (or on a host without qemu-x86_64) ships without them.  This tool closes that
# gap two ways:
#
#   --stage-only            (Re)generate the caches into the staging tree only.
#   --image <data.img>      Also inject the staged caches into an existing ext2
#                           image in place via debugfs -w (unprivileged, no
#                           mount, no rebuild).  Operates on a COPY unless
#                           --in-place is given.
#
# Cache generation reuses the staged Alpine rootfs tools under qemu-x86_64
# user-mode emulation, exactly as install-firefox-musl.sh does.  When
# qemu-x86_64 is unavailable, the loaders.cache built-in-only fallback is still
# written (sufficient for the PNG/JPEG titlebar icons); gschemas.compiled and
# mime.cache cannot be produced without it.
#
# All output is structured "[GUI-CACHE] ..." lines; the tool is non-interactive
# and one-shot.  Refs: gdk-pixbuf-query-loaders(1), glib-compile-schemas(1),
# update-mime-database(1) (freedesktop.org Shared MIME-info spec), debugfs(8),
# mke2fs(8) -d.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Defaults (overridable by flags / env).
BUILD_DIR="${ASTRYXOS_BUILD_DIR:-${ROOT_DIR}/build}"
DISK_DIR="${BUILD_DIR}/disk"
ROOTFS="${ASTRYXOS_FIREFOX_ROOTFS:-${HOME}/.cache/astryxos-firefox-musl/rootfs}"
IMAGE=""
IN_PLACE=0
STAGE_ONLY=0
REGEN=1   # regenerate into staging by default; --no-regen injects existing staged caches

usage() {
    cat <<EOF
Usage: patch-gui-caches.sh [options]

  --stage-only           Regenerate caches into the staging tree only (no image).
  --image <data.img>     Inject the staged caches into this ext2 image.
  --in-place             With --image: modify the image in place (default: a
                         "<image>.gui-cached" copy is produced and patched).
  --no-regen             Skip regeneration; inject whatever is already staged.
  --disk-dir <dir>       Staging tree (default: ${DISK_DIR}).
  --rootfs <dir>         Alpine rootfs with the musl gen tools
                         (default: ${ROOTFS}).
  -h, --help             This help.

Exit status: 0 on success; non-zero if a requested cache could not be produced
or the image injection failed.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --stage-only) STAGE_ONLY=1; shift ;;
        --image) IMAGE="${2:?--image needs a path}"; shift 2 ;;
        --in-place) IN_PLACE=1; shift ;;
        --no-regen) REGEN=0; shift ;;
        --disk-dir) DISK_DIR="${2:?--disk-dir needs a path}"; shift 2 ;;
        --rootfs) ROOTFS="${2:?--rootfs needs a path}"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "[GUI-CACHE] ERROR: unknown arg '$1'" >&2; usage >&2; exit 2 ;;
    esac
done

DISK_USR_LIB="${DISK_DIR}/usr/lib"
DISK_USR_SHARE="${DISK_DIR}/usr/share"
GDKP_DIR="${DISK_USR_LIB}/gdk-pixbuf-2.0/2.10.0"
GSCHEMA_DIR="${DISK_USR_SHARE}/glib-2.0/schemas"
MIME_DIR="${DISK_USR_SHARE}/mime"

LOADERS_CACHE="${GDKP_DIR}/loaders.cache"
GSCHEMA_CACHE="${GSCHEMA_DIR}/gschemas.compiled"
MIME_CACHE="${MIME_DIR}/mime.cache"

have_qemu() { command -v qemu-x86_64 >/dev/null 2>&1; }

# The staged Alpine tool binaries (gdk-pixbuf-query-loaders, glib-compile-schemas,
# update-mime-database) DT_NEEDED glib (libglib/libgio/libgobject/libgmodule/
# libintl).  The cached bootstrap rootfs may carry a different glib build than
# the staging tree's FF-matched one, which surfaces as musl relocation errors
# ("symbol not found") under qemu.  Point the in-emulator loader at the staging
# tree's libs first so the tools resolve against the exact glib that ships in
# the image.  Falls back to the rootfs's own libs when the staging libs are
# absent.
QEMU_LDPATH="${DISK_USR_LIB}:${DISK_DIR}/lib"
run_under_qemu() {  # run_under_qemu <KEY=VAL extra env pairs...> -- <argv...>
    # Each pre-"--" token is an environment assignment passed to qemu-user via
    # -E (qemu-x86_64 needs the -E flag per VALUE; a bare KEY=VAL would be taken
    # as the program to exec).  LD_LIBRARY_PATH points the in-emulator loader at
    # the staging tree libs first.
    local eflags=("-E" "LD_LIBRARY_PATH=${QEMU_LDPATH}")
    while [ "$1" != "--" ]; do eflags+=("-E" "$1"); shift; done
    shift
    qemu-x86_64 -L "${ROOTFS}" "${eflags[@]}" "$@"
}

# ── built-in loader stanza emitter (mirrors install-firefox-musl.sh c1) ──────
append_builtin_loader_stanzas() {
    local cache_file="$1" added=0
    local gdkp_lib="${DISK_USR_LIB}/libgdk_pixbuf-2.0.so.0"
    if [ -f "${gdkp_lib}" ] && readelf -dW "${gdkp_lib}" 2>/dev/null | grep -q 'NEEDED.*libpng16'; then
        if ! grep -q '^"png"' "${cache_file}" 2>/dev/null; then
            printf '%s\n' \
'"/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so"' \
'"png" 5 "gdk-pixbuf" "PNG" "LGPL"' \
'"image/png" ""' \
'"png" ""' \
'"\211PNG\r\n\032\n" "" 100' \
'' >> "${cache_file}"
            added=$((added + 1))
        fi
    fi
    if [ -f "${gdkp_lib}" ] && readelf -dW "${gdkp_lib}" 2>/dev/null | grep -q 'NEEDED.*libjpeg'; then
        if ! grep -q '^"jpeg"' "${cache_file}" 2>/dev/null; then
            printf '%s\n' \
'"/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so"' \
'"jpeg" 5 "gdk-pixbuf" "JPEG" "LGPL"' \
'"image/jpeg" ""' \
'"jpeg" "jpe" "jpg" ""' \
'"\377\330" "" 100' \
'' >> "${cache_file}"
            added=$((added + 1))
        fi
    fi
    echo "${added}"
}

regen_loaders() {
    local query="${ROOTFS}/usr/bin/gdk-pixbuf-query-loaders"
    [ -d "${GDKP_DIR}/loaders" ] || { echo "[GUI-CACHE] skip loaders.cache: no loaders/ dir in staging"; return 0; }
    mkdir -p "${GDKP_DIR}"
    if [ -x "${query}" ] && have_qemu; then
        if run_under_qemu \
             "GDK_PIXBUF_MODULEDIR=${ROOTFS}/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders" \
             -- "${query}" 2>/dev/null \
           | sed "s|${ROOTFS}/usr/lib/gdk-pixbuf-2.0|/usr/lib/gdk-pixbuf-2.0|g; s|^# LoaderDir = ${ROOTFS}|# LoaderDir = |" \
             > "${LOADERS_CACHE}.tmp" 2>/dev/null \
           && grep -q '^"/usr/lib/gdk-pixbuf-2.0' "${LOADERS_CACHE}.tmp"; then
            local added; added="$(append_builtin_loader_stanzas "${LOADERS_CACHE}.tmp")"
            mv -f "${LOADERS_CACHE}.tmp" "${LOADERS_CACHE}"
            echo "[GUI-CACHE] regenerated loaders.cache ($(grep -c '^"/usr/lib' "${LOADERS_CACHE}") loaders incl ${added} built-in)"
            return 0
        fi
        rm -f "${LOADERS_CACHE}.tmp" 2>/dev/null || true
    fi
    # built-in-only fallback (qemu absent or query failed)
    { echo '# GdkPixbuf Image Loader Modules file'
      echo '# Automatically generated file, do not edit'
      echo '# Created by patch-gui-caches.sh (built-in loaders only)'
      echo '#'; } > "${LOADERS_CACHE}.tmp"
    local added; added="$(append_builtin_loader_stanzas "${LOADERS_CACHE}.tmp")"
    if [ "${added}" -gt 0 ]; then
        mv -f "${LOADERS_CACHE}.tmp" "${LOADERS_CACHE}"
        echo "[GUI-CACHE] wrote built-in-only loaders.cache (${added} loaders; qemu-x86_64 absent or query failed)"
    else
        rm -f "${LOADERS_CACHE}.tmp" 2>/dev/null || true
        echo "[GUI-CACHE] WARNING: could not produce loaders.cache (no built-in PNG/JPEG loaders detected)"
    fi
}

regen_gschema() {
    local tool="${ROOTFS}/usr/bin/glib-compile-schemas"
    [ -d "${GSCHEMA_DIR}" ] && ls "${GSCHEMA_DIR}"/*.gschema.xml >/dev/null 2>&1 \
        || { echo "[GUI-CACHE] skip gschemas.compiled: no *.gschema.xml in staging"; return 0; }
    if [ -x "${tool}" ] && have_qemu; then
        if run_under_qemu -- "${tool}" "${GSCHEMA_DIR}" >/dev/null 2>&1 && [ -f "${GSCHEMA_CACHE}" ]; then
            echo "[GUI-CACHE] regenerated gschemas.compiled ($(stat -c%s "${GSCHEMA_CACHE}") bytes)"
        else
            echo "[GUI-CACHE] WARNING: glib-compile-schemas failed — gschemas.compiled not produced"
        fi
    else
        echo "[GUI-CACHE] WARNING: cannot produce gschemas.compiled (need qemu-x86_64 + ${tool})"
    fi
}

regen_mime() {
    local tool="${ROOTFS}/usr/bin/update-mime-database"
    [ -d "${MIME_DIR}" ] || { echo "[GUI-CACHE] skip mime.cache: no mime/ dir in staging"; return 0; }
    if [ -x "${tool}" ] && have_qemu; then
        if run_under_qemu -- "${tool}" "${MIME_DIR}" >/dev/null 2>&1 && [ -f "${MIME_CACHE}" ]; then
            echo "[GUI-CACHE] regenerated mime.cache ($(stat -c%s "${MIME_CACHE}") bytes)"
        else
            echo "[GUI-CACHE] WARNING: update-mime-database failed — mime.cache not produced"
        fi
    else
        echo "[GUI-CACHE] WARNING: cannot produce mime.cache (need qemu-x86_64 + ${tool})"
    fi
}

# ── inject a staged file into the ext2 image at its absolute disk path ───────
# debugfs -w write needs the parent dir to exist; create it (and intermediates)
# defensively, then overwrite (rm -f first so re-runs are idempotent).
inject_into_image() {
    local img="$1" staged="$2" abs="$3"   # abs is the path inside the image, e.g. /usr/share/mime/mime.cache
    [ -f "${staged}" ] || { echo "[GUI-CACHE] inject skip ${abs}: not staged"; return 0; }
    local dir; dir="$(dirname "${abs}")"
    # Ensure each parent dir exists (mkdir is a no-op-with-error if present; ignore).
    local p="" seg
    IFS='/' read -ra _segs <<< "${dir#/}"
    for seg in "${_segs[@]}"; do
        p="${p}/${seg}"
        debugfs -w -R "mkdir ${p}" "${img}" >/dev/null 2>&1 || true
    done
    debugfs -w -R "rm ${abs}" "${img}" >/dev/null 2>&1 || true
    if debugfs -w -R "write ${staged} ${abs}" "${img}" 2>&1 | grep -qiE 'error|not'; then
        echo "[GUI-CACHE] ERROR: debugfs write failed for ${abs}"
        return 1
    fi
    # Verify it landed.
    if debugfs -R "stat ${abs}" "${img}" 2>/dev/null | grep -q 'Inode:'; then
        echo "[GUI-CACHE] injected ${abs} ($(stat -c%s "${staged}") bytes)"
    else
        echo "[GUI-CACHE] ERROR: ${abs} not present after debugfs write"
        return 1
    fi
}

# ── main ─────────────────────────────────────────────────────────────────────
echo "[GUI-CACHE] staging tree: ${DISK_DIR}"
echo "[GUI-CACHE] rootfs:       ${ROOTFS} (qemu-x86_64: $(have_qemu && echo present || echo ABSENT))"

if [ "${REGEN}" -eq 1 ]; then
    regen_loaders
    regen_gschema
    regen_mime
fi

# Report staged state + count what we actually have.
staged_ok=0; staged_total=3
for c in "${LOADERS_CACHE}" "${GSCHEMA_CACHE}" "${MIME_CACHE}"; do
    [ -f "${c}" ] && staged_ok=$((staged_ok + 1))
done
echo "[GUI-CACHE] staged: ${staged_ok}/${staged_total} cache files present"

if [ "${STAGE_ONLY}" -eq 1 ] || [ -z "${IMAGE}" ]; then
    [ "${staged_ok}" -eq "${staged_total}" ] && exit 0 || exit 1
fi

# Image injection.
[ -f "${IMAGE}" ] || { echo "[GUI-CACHE] ERROR: image not found: ${IMAGE}"; exit 1; }
command -v debugfs >/dev/null 2>&1 || { echo "[GUI-CACHE] ERROR: debugfs not found (apt-get install e2fsprogs)"; exit 1; }

TARGET="${IMAGE}"
if [ "${IN_PLACE}" -eq 0 ]; then
    TARGET="${IMAGE}.gui-cached"
    echo "[GUI-CACHE] copying ${IMAGE} -> ${TARGET} (use --in-place to patch the original)"
    cp -f --reflink=auto "${IMAGE}" "${TARGET}"
fi

rc=0
inject_into_image "${TARGET}" "${LOADERS_CACHE}" "/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" || rc=1
inject_into_image "${TARGET}" "${GSCHEMA_CACHE}"  "/usr/share/glib-2.0/schemas/gschemas.compiled" || rc=1
inject_into_image "${TARGET}" "${MIME_CACHE}"     "/usr/share/mime/mime.cache" || rc=1

echo "[GUI-CACHE] image patched: ${TARGET} (rc=${rc})"
exit "${rc}"
